### ISSUE TITLE
Why is that?

### ISSUE THREAD

**Issue by CryXE** [pyturtle/Overwatch2-colorbot-Cheats#9]

**Comment by CryXE** [comment]
Exception ignored in: <function _compointer_base.__del__ at 0x0000017917AB5BC0>
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\__init__.py", line 614, in __del__
    self.Release()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\__init__.py", line 847, in Release
    return self.__com_Release()
           ^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation writing 0x0000000000000000
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 179, in __capture
    self.__frame_buffer[self.__head] = frame
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (360,640,4) into shape (1080,1920,4)

Exception in thread DXCamera:
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 208, in __capture
    self.stop()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 142, in stop
    self.__thread.join(timeout=10)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1109, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
